# Generated by Django 4.1.7 on 2023-04-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_profile_subscriptionplan_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.subscriptionplan'),
        ),
    ]
